baseURL = "https://adamcook.io/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Adam Cook"
theme = "hugo-theme-stack"
disqusShortname = "adam-cook"

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[params]
    mainSections = ["post"]
    rssFullContent = true

    [params.dateFormat]
        published = "2 January 2006"
        lastUpdated = "2 January 2006"

    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""

    [params.comments]
        enabled = true
        provider = "disqus"

    [params.sidebar]
        emoji = "🙃"
        avatar = "img/avatar.png"
        subtitle = "Passionate about helping people. #PowerShell, #ConfigMgr and #Azure. Misses #Linux."

    [params.widgets]
        enabled = ['archives']
        [params.widgets.archives]
            limit = 99
            ### Archives page relative URL
            path = "archives"

    [params.opengraph]
        [params.opengraph.twitter]
            site = "codaamok"
            card = "summary"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives"
        weight = -98
        pre = "archives"
    [[menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/codaamok"
        weight = -93
        pre = "twitter"
    [[menu.main]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/codaamok"
        weight = -92
        pre = "github"
    [[menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://linkedin.com/in/adamcharlescook"
        weight = -91
        pre = "linkedin"
    [[menu.main]]
        identifier = "youtube"
        name = "YouTube"
        url = "https://www.youtube.com/channel/UCjv4o4ToaauMNKP4wfIhP0A"
        weight = -90
        pre = "youtube"
    [[menu.main]]
        identifier = "pssouth"
        name = "PowerShell Southampton"
        url = "https://pssouth.co.uk"
        weight = -80
        pre = "prompt"
    